force-app/main/default/objects/MM_Question__c/MM_Question__c.object-meta.xml
<CustomObject>
    <description>Stores individual questions and their configuration. Supports multiple answer types</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_Question_Option__c/MM_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Question Option</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_Response_Session__c/MM_Response_Session__c.object-meta.xml
<CustomObject>
    <description>Tracks a user’s completion of a questionnaire</description>
    <label>Response Session</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_Response_Session__c/fields/MM_User__c.field-meta.xml
<CustomField>
    <fullName>MM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MM User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Response Sessions</relationshipLabel>
    <relationshipName>Response_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/MM_User_Response__c.object-meta.xml
<CustomObject>
    <description>Stores answers to individual questions. Dynamically handles different question types.</description>
    <label>User Response</label>
    <nameField>
        <displayFormat>URES-{0000}</displayFormat>
        <label>User Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Option_Text__c.field-meta.xml
<CustomField>
    <fullName>MM_Option_Text__c</fullName>
    <formula>MM_Selected_Option__r.MM_Option_Text__c</formula>
    <label>Option Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Question__c.field-meta.xml
<CustomField>
    <fullName>MM_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>MM_Question__c</referenceTo>
    <relationshipLabel>User Responses</relationshipLabel>
    <relationshipName>User_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Question_Text__c.field-meta.xml
<CustomField>
    <fullName>MM_Question_Text__c</fullName>
    <formula>MM_Question__r.MM_QuestionText__c</formula>
    <label>Question Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Response_Session__c.field-meta.xml
<CustomField>
    <fullName>MM_Response_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Session</label>
    <referenceTo>MM_Response_Session__c</referenceTo>
    <relationshipLabel>User Responses</relationshipLabel>
    <relationshipName>User_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Selected_Option__c.field-meta.xml
<CustomField>
    <fullName>MM_Selected_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Option</label>
    <referenceTo>MM_Question_Option__c</referenceTo>
    <relationshipLabel>User Responses</relationshipLabel>
    <relationshipName>User_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response_Options__c/MM_User_Response_Options__c.object-meta.xml
<CustomObject>
    <label>User Response Option</label>
    <nameField>
        <displayFormat>URO-{00000}</displayFormat>
        <label>User Response Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Response Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_User_Response_Options__c/fields/MM_Question__c.field-meta.xml
<CustomField>
    <fullName>MM_Question__c</fullName>
    <label>Question</label>
    <referenceTo>MM_Question__c</referenceTo>
    <relationshipLabel>User Response Options</relationshipLabel>
    <relationshipName>User_Response_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MM_User_Response_Options__c/fields/MM_Question_Option__c.field-meta.xml
<CustomField>
    <fullName>MM_Question_Option__c</fullName>
    <label>Question Option</label>
    <referenceTo>MM_Question_Option__c</referenceTo>
    <relationshipLabel>User Response Options</relationshipLabel>
    <relationshipName>User_Response_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MindMentor/AgentUtilities.cls
public with sharing class AgentUtilities {
  public static string getResponseSession(string userId) {
    List<MM_Response_Session__c> responseSession = new List<MM_Response_Session__c>();
    responseSession = [
      SELECT
        Id,
        (
          SELECT MM_Question_Text__c, MM_Selected_Option__r.MM_Option_Text__c
          FROM User_Responses__r
        ),
        (
          SELECT
            MM_Question__r.MM_QuestionText__c,
            MM_Question_Option__r.MM_Option_Text__c
          FROM User_Response_Options__r
        )
      FROM MM_Response_Session__c
      WHERE MM_User__c = :userId
      WITH USER_MODE
      ORDER BY createdDate DESC
    ];
    return JSON.serialize(responseSession);
  }
}