force-app/main/default/objects/MM_Question__c/MM_Question__c.object-meta.xml
<CustomObject>
    <description>Stores individual questions and their configuration. Supports multiple answer types</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_Question_Option__c/MM_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Question Option</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_Question_Option__c/fields/MM_Question__c.field-meta.xml
<CustomField>
    <fullName>MM_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>MM_Question__c</referenceTo>
    <relationshipLabel>Question Options</relationshipLabel>
    <relationshipName>Question_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_Response_Session__c/MM_Response_Session__c.object-meta.xml
<CustomObject>
    <description>Tracks a user’s completion of a questionnaire</description>
    <label>Response Session</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_User_Response__c/MM_User_Response__c.object-meta.xml
<CustomObject>
    <description>Stores answers to individual questions. Dynamically handles different question types.</description>
    <label>User Response</label>
    <nameField>
        <displayFormat>URES-{0000}</displayFormat>
        <label>User Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Question__c.field-meta.xml
<CustomField>
    <fullName>MM_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>MM_Question__c</referenceTo>
    <relationshipLabel>User Responses</relationshipLabel>
    <relationshipName>User_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response__c/fields/MM_Response_Session__c.field-meta.xml
<CustomField>
    <fullName>MM_Response_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response Session</label>
    <referenceTo>MM_Response_Session__c</referenceTo>
    <relationshipLabel>User Responses</relationshipLabel>
    <relationshipName>User_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MM_User_Response_Options__c/MM_User_Response_Options__c.object-meta.xml
<CustomObject>
    <label>User Response Option</label>
    <nameField>
        <displayFormat>URO-{00000}</displayFormat>
        <label>User Response Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Response Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MM_User_Response_Options__c/fields/MM_Question__c.field-meta.xml
<CustomField>
    <fullName>MM_Question__c</fullName>
    <label>Question</label>
    <referenceTo>MM_Question__c</referenceTo>
    <relationshipLabel>User Response Options</relationshipLabel>
    <relationshipName>User_Response_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MM_User_Response_Options__c/fields/MM_Question_Option__c.field-meta.xml
<CustomField>
    <fullName>MM_Question_Option__c</fullName>
    <label>Question Option</label>
    <referenceTo>MM_Question_Option__c</referenceTo>
    <relationshipLabel>User Response Options</relationshipLabel>
    <relationshipName>User_Response_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MindMentor/CheckObjectAccess.cls
/**
 * @description       : A utility class to check access for specific Salesforce objects.
 *                      This class provides static methods to verify if the current user has read access
 *                      to the User, MM_Response_Session__c, and MM_User_Response__c objects.
 *                      If access is insufficient, an AuraHandledException is thrown with a relevant message.
 * @author            : Abhinav Singh
 * @group             : MindMentor
 * @last modified on  : 01-09-2026
 * @last modified by  : Abhinav Singh
**/
public with sharing class CheckObjectAccess {
    /**
     * @description Checks if the current user has access to the User object.
     */
    public static void checkUserAccess() {
        if (!Schema.sObjectType.User.isAccessible() && !Schema.sObjectType.User.isCreateable() && !Schema.sObjectType.User.isUpdateable() && !Schema.sObjectType.User.isDeletable() && !Schema.sObjectType.User.isSearchable()) {
            throw new AuraHandledException('Insufficient access to User object.');
        }
    }

    /**
     * @description Checks if the current user has access to the MM_Response_Session__c object.
     */
    public static void checkSessionAccess() {
        if (!Schema.sObjectType.MM_Response_Session__c.isAccessible() && !Schema.sObjectType.MM_Response_Session__c.isCreateable() && !Schema.sObjectType.MM_Response_Session__c.isUpdateable() && !Schema.sObjectType.MM_Response_Session__c.isDeletable() && !Schema.sObjectType.MM_Response_Session__c.isSearchable()) {
            throw new AuraHandledException('Insufficient access to MM_Response_Session__c object.');
        }
    }

    /**
     * @description Checks if the current user has access to the MM_User_Response__c object.
     */
    public static void checkUserResponseAccess() {
        if (!Schema.sObjectType.MM_User_Response__c.isAccessible() && !Schema.sObjectType.MM_User_Response__c.isCreateable() && !Schema.sObjectType.MM_User_Response__c.isUpdateable() && !Schema.sObjectType.MM_User_Response__c.isDeletable() && !Schema.sObjectType.MM_User_Response__c.isSearchable()) {
            throw new AuraHandledException('Insufficient access to MM_User_Response__c object.');
        }
    }
    /**
     * @description Checks if the current user has access to the MM_Question__c object.
     */
    public static void checkQuestionAccess() {
        if (!Schema.sObjectType.MM_Question__c.isAccessible() && !Schema.sObjectType.MM_Question__c.isCreateable() && !Schema.sObjectType.MM_Question__c.isUpdateable() && !Schema.sObjectType.MM_Question__c.isDeletable() && !Schema.sObjectType.MM_Question__c.isSearchable()){
            throw new AuraHandledException('Insufficient access to MM_Question__c object.');
        }
    }

    /**
     * @description Checks if the current user has access to the MM_Question_Option__c object.
     */
    public static void checkQuestionOptionAccess() {
        if (!Schema.sObjectType.MM_Question_Option__c.isAccessible() && !Schema.sObjectType.MM_Question_Option__c.isCreateable() && !Schema.sObjectType.MM_Question_Option__c.isUpdateable() && !Schema.sObjectType.MM_Question_Option__c.isDeletable() && !Schema.sObjectType.MM_Question_Option__c.isSearchable() ){
            throw new AuraHandledException('Insufficient access to MM_Question_Option__c object.');
        }
    }

    /**
     * @description Checks if the current user has access to the MM_User_Response_Options__c object.
     */
    public static void checkUserResponseOptionsAccess() {
        if (!Schema.sObjectType.MM_User_Response_Options__c.isAccessible() && !Schema.sObjectType.MM_User_Response_Options__c.isCreateable() && !Schema.sObjectType.MM_User_Response_Options__c.isUpdateable() && !Schema.sObjectType.MM_User_Response_Options__c.isDeletable() && !Schema.sObjectType.MM_User_Response_Options__c.isSearchable() ){
            throw new AuraHandledException('Insufficient access to MM_User_Response_Options__c object.');
        }
    }
}